### ISSUE TITLE
Log something when catching exceptions outside of the handler

### ISSUE THREAD

**Issue by ikben** [aws-cloudformation/cloudformation-cli-python-plugin#60] opened 2019-11-24 20:57 UTC
(I know this is still beta, I'm logging everything I run into during testing)

Currently uncaught exceptions are handled by the library. This is great, because it means I can't forget to write a try/except around the whole method.

However when this happens nothing is logged about the underlying exception. So it's impossible to see what went wrong without deploying a new version that catches all exceptions and logs them inside the handler.

It would be nice if we could have a log of unexpected exceptions without boilerplate code in every handler

**Comment by tobywf** [comment] 2019-11-25 01:24
looks like the issue is the logging that's there isn't set up for cross-account log delivery. may have overlooked when that was set up in #36 .

**Comment by tobywf** [comment] 2019-11-28 01:14
With PR #64 , I actually do get uncaught errors delivered:

```
Exception caught
Traceback (most recent call last): File "/var/task/cloudformation_cli_python_lib/resource.py", line 216, in __call__ progress = self._invoke_handler(caller_sess, request, action, callback) File "/var/task/cloudformation_cli_python_lib/resource.py", line 123, in _invoke_handler progress = handler(session, request, callback_context) File "/var/task/test_me_python/handl
Exception caught
Traceback (most recent call last):
  File "/var/task/cloudformation_cli_python_lib/resource.py", line 216, in __call__
    progress = self._invoke_handler(caller_sess, request, action, callback)
  File "/var/task/cloudformation_cli_python_lib/resource.py", line 123, in _invoke_handler
    progress = handler(session, request, callback_context)
  File "/var/task/test_me_python/handlers.py", line 29, in create_handler
    raise ValueError("foo")
ValueError: foo
```

So I think we can close this soon!

**Closed** 2019-11-29 19:46 UTC
