### ISSUE TITLE
Add fields to ResourceHandlerRequest

### ISSUE THREAD

**Issue by benkehoe** [aws-cloudformation/cloudformation-cli-python-plugin#86] opened 2020-04-01 13:24 UTC
The `ResourceHandlerRequest` [implementation in the Java plugin](https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/blob/86babd0a576407976fe9569449b1b860664bb775/src/main/java/software/amazon/cloudformation/proxy/ResourceHandlerRequest.java#L34) has more fields, including tags, accountId, and partition. These should be present on `ResourceHandlerRequest` in Python as well.

**Comment by LaikaN57** [comment] 2020-07-16 07:41
@ammokhov And it looks like this is now a duplicate of #107 as well which just got merged. Looks like we have reached parity with the java plugin too 👍

**Comment by ammokhov** [comment] 2020-07-16 21:16
closing as #107 fixed the issue

**Closed by ammokhov** 2020-07-16 21:16 UTC
