### ISSUE TITLE
Unhandled Exception on 'cfn submit --dry-run' - related to transient editor symlink

### ISSUE THREAD

**Issue by mikemccabe** [aws-cloudformation/cloudformation-cli-python-plugin#77] opened 2020-02-20 20:11 UTC
cfn submit --dry-run
Starting Docker build. This may take several minutes if the image 'lambci/lambda:build-python3.7' needs to be pulled first.
=== Unhandled exception ===
Please report this issue to the team.
Issue tracker: https://github.com/aws-cloudformation/aws-cloudformation-rpdk/issues
Please include the log file 'rpdk.log'

**Comment by jotompki** [comment] 2020-02-20 20:17
Rerouted this to the python repo as it is an error with the packaging of the handler before submitting. Will look into this.

Log error of note:

```
shutil.Error: [('/Users/mmccabe/src/python_walkthru/src/mike_ec2_keypair/.#handlers.py', '/Users/mmccabe/src/python_walkthru/build/mike_ec2_keypair/.#handlers.py', "[Errno 2] No such file or directory: '/Users/mmccabe/src/python_walkthru/src/mike_ec2_keypair/.#handlers.py'")]
```

**Comment by mikemccabe** [comment] 2020-02-20 20:24
```ls -la src/mike_ec2_keypair/
total 64
-rw-r--r--   1 mmccabe  staff  4941 Feb 20 12:06 #handlers.py#
drwxr-xr-x  10 mmccabe  staff   320 Feb 20 12:06 .
lrwxr-xr-x   1 mmccabe  staff    26 Feb 20 12:05 .#handlers.py -> mmccabe@mmccabe.local.2756
drwxr-xr-x   3 mmccabe  staff    96 Feb 19 18:31 ..
-rw-r--r--   1 mmccabe  staff     0 Feb 19 15:51 __init__.py
-rw-r--r--   1 mmccabe  staff  4941 Feb 19 21:11 handlers.py
-rw-r--r--   1 mmccabe  staff  3027 Feb 19 16:31 handlers_orig.py
-rw-r--r--   1 mmccabe  staff  3027 Feb 19 16:29 handlers_orig.py~
-rw-r--r--   1 mmccabe  staff  1367 Feb 19 15:56 models.py
-rw-r--r--   1 mmccabe  staff  2993 Feb 19 18:30 rpdk.log```

So, I'm editing with Emacs, and the buffer for handlers.py had an unsaved change (a stray keystroke).  After I undid the change in Emacs (no save needed) the .#handlers.py link disappeared, and cfn submit --dry-run succeeded.

Please don't say 'don't do that' :)

I'm able to keep working after diagnosing this, but I expect I'm not the only person that will run into this issue.

Thanks for this tool!

**Comment by ammokhov** [comment] 2020-09-23 06:11
> ```livescript
> total 64
> -rw-r--r--   1 mmccabe  staff  4941 Feb 20 12:06 #handlers.py#
> drwxr-xr-x  10 mmccabe  staff   320 Feb 20 12:06 .
> lrwxr-xr-x   1 mmccabe  staff    26 Feb 20 12:05 .#handlers.py -> mmccabe@mmccabe.local.2756
> drwxr-xr-x   3 mmccabe  staff    96 Feb 19 18:31 ..
> -rw-r--r--   1 mmccabe  staff     0 Feb 19 15:51 __init__.py
> -rw-r--r--   1 mmccabe  staff  4941 Feb 19 21:11 handlers.py
> -rw-r--r--   1 mmccabe  staff  3027 Feb 19 16:31 handlers_orig.py
> -rw-r--r--   1 mmccabe  staff  3027 Feb 19 16:29 handlers_orig.py~
> -rw-r--r--   1 mmccabe  staff  1367 Feb 19 15:56 models.py
> -rw-r--r--   1 mmccabe  staff  2993 Feb 19 18:30 rpdk.log
> ```
> 
> So, I'm editing with Emacs, and the buffer for handlers.py had an unsaved change (a stray keystroke). After I undid the change in Emacs (no save needed) the .#handlers.py link disappeared, and cfn submit --dry-run succeeded.
> 
> Please don't say 'don't do that' :)
> 
> I'm able to keep working after diagnosing this, but I expect I'm not the only person that will run into this issue.
> 
> Thanks for this tool!

are you still having this issue?

**Comment by mikemccabe** [comment] 2020-09-23 15:45
Hi, thanks for checking in on this.  I'm no longer with the organization where I was working on this project, so I can't test it easily.

The error was quite robust when I encountered it; with a file open in Emacs with an uncommitted change, cfn submit failed.

**Comment by ammokhov** [comment] 2020-09-23 16:07
> Hi, thanks for checking in on this.  I'm no longer with the organization where I was working on this project, so I can't test it easily.
> 
> 
> 
> The error was quite robust when I encountered it; with a file open in Emacs with an uncommitted change, cfn submit failed.

That was most likely caused by the incorrect version we had for some time but should be fixed we the latest release. I will close this issue for now but feel free to reopen if you still experience it

**Closed by ammokhov** 2020-09-23 16:07 UTC
Labels: question
